# Generated by Django 5.0.1 on 2025-11-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.shoptype'),
        ),
    ]
