# Generated by Django 5.0.1 on 2025-11-17 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_name', models.CharField(max_length=255)),
                ('available_chairs', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_model', models.CharField(choices=[('Fixed Pay', 'Fixed Pay'), ('Commission Pay', 'Commission Pay')], max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_unit', models.CharField(choices=[('Hourly', 'Hourly'), ('Percentage', 'Percentage'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20)),
                ('availability_start_date', models.DateTimeField()),
                ('availability_end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('cover_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status', 'availability_end_date'], name='jobs_shop_id_7d51a6_idx'), models.Index(fields=['status', 'availability_end_date', 'created_at'], name='jobs_status_23ebfb_idx'), models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'), models.Index(fields=['shop', 'status', 'availability_end_date', 'created_at'], name='jobs_shop_id_ef4dcb_idx')],
            },
        ),
    ]
