# Generated by Django 5.0.1 on 2025-11-17 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('property_listing_type', models.CharField(choices=[('agent', 'Agent'), ('shop', 'Shop')], max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_area', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sqft_area', models.CharField(blank=True, max_length=50, null=True)),
                ('zoning_type', models.CharField(choices=[('Commercial/Barber Permitted', 'Commercial/Barber Permitted'), ('Commercial/Salon Permitted', 'Commercial/Salon Permitted'), ('Commercial', 'Commercial'), ('Mixed-use', 'Mixed-use'), ('Industrial', 'Industrial')], max_length=50)),
                ('property_type', models.CharField(choices=[('Real Estate', 'Real Estate'), ('Private Suite', 'Private Suite')], max_length=20)),
                ('pricing_model', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=20)),
                ('pricing_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pricing_currency', models.CharField(default='USD', max_length=3)),
                ('pricing_rent_frequency', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True)),
                ('rent_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('security_deposit', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_terms', models.JSONField(blank=True, default=list)),
                ('listing_start_date', models.DateTimeField(auto_now_add=True)),
                ('listing_end_date', models.DateTimeField()),
                ('listing_is_active', models.BooleanField(default=True)),
                ('media_images', models.JSONField(blank=True, default=list)),
                ('media_videos', models.JSONField(blank=True, default=list)),
                ('media_virtual_tour', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='common.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'real_estate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['address_latitude', 'address_longitude', 'status', 'listing_is_active'], name='real_estate_address_0f7a0c_idx'), models.Index(fields=['owner', 'status', 'created_at'], name='real_estate_owner_i_83a710_idx'), models.Index(fields=['zoning_type', 'property_type', 'property_listing_type', 'status'], name='real_estate_zoning__a4b0b8_idx'), models.Index(fields=['pricing_model', 'pricing_amount', 'status'], name='real_estate_pricing_8d693f_idx')],
            },
        ),
    ]
